module Types where

-- WARNING: DO NOT EDIT THIS FILE FOR *ANY* REASON, ANY CHANGES WILL BE DISCARDED
--          YOU WILL BE PENALISED IF YOU CODE NO LONGER COMPILES.

type Coefficient = Rational
type Exponent = Integer
type Term = (Coefficient, Exponent)
type Polynomial = [Term]
data Expr = P Polynomial
          | Add Expr Expr
          | Mul Expr Expr
          | Pow Expr Rational
          | Log Expr
          deriving (Eq, Ord, Show)
